# Generated by Django 3.2.2 on 2021-05-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('pub_date', models.DateTimeField(verbose_name='작성일자')),
                ('author', models.CharField(max_length=15, verbose_name='작성자')),
                ('content', models.TextField(verbose_name='내용')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='평점')),
                ('place_id', models.IntegerField(default=0)),
                ('mainphoto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
