# Generated by Django 3.2 on 2021-06-27 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일자')),
                ('modified_date', models.DateTimeField(null=True, verbose_name='수정일자')),
                ('content', models.TextField(max_length=300, verbose_name='내용')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='평점')),
                ('place_id', models.IntegerField(default=0)),
                ('author', models.ForeignKey(db_column='author', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
