# Generated by Django 3.2.2 on 2021-05-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(max_length=300, verbose_name='내용'),
        ),
    ]
