# Generated by Django 3.2.2 on 2021-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='place_id',
            field=models.IntegerField(default=0),
        ),
    ]
