# Generated by Django 3.2.2 on 2021-05-20 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 0, 4, 42, 540128), verbose_name='작성일자'),
        ),
    ]
