# Generated by Django 3.2.2 on 2021-05-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='author_id',
        ),
    ]
