# Generated by Django 3.2.2 on 2021-05-31 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='수정일자'),
        ),
    ]
