# Generated by Django 3.2.2 on 2021-05-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='modified_date',
            field=models.DateTimeField(null=True, verbose_name='수정일자'),
        ),
    ]
