# Generated by Django 3.2.2 on 2021-05-26 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20210526_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(db_column='author', default='anonymous', on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='작성자'),
            preserve_default=False,
        ),
    ]
