# Generated by Django 3.2.2 on 2021-05-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_posts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.CharField(max_length=25, null=True, verbose_name='작성자'),
        ),
    ]
