# Generated by Django 3.2 on 2021-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='a76b0618-aab2-4cf9-abaa-f3175b4d6bf6', primary_key=True, serialize=False),
        ),
    ]
