# Generated by Django 3.2.2 on 2021-05-26 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c95acc44-9fb7-4e32-8bef-aa2c4f447a1e')),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Usr Name'),
        ),
    ]
