# Generated by Django 3.2 on 2021-05-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authentication',
            field=models.BooleanField(default=False),
        ),
    ]
