# Generated by Django 3.2 on 2021-05-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_authentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_authentication',
            field=models.BooleanField(default=True),
        ),
    ]
